ARG CUDA_IMAGE="12.2.2-devel-ubuntu22.04"
FROM --platform=amd64 nvidia/cuda:${CUDA_IMAGE}

## Top level args / env vars
ARG USER=user
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DEBIAN_FRONTEND=noninteractive

## Install python + opencl + blas
RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y git build-essential ca-certificates \
    python3 python3-dev python3-pip python-is-python3 gcc wget \
    && rm -rf /var/lib/apt/lists/*

## Apt based dependencies
RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get -y install \
    curl \
    git \
    vim \
    wget \
    procps \
    inotify-tools \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

## Create unpriv user
RUN groupadd --gid $USER_GID $USER \
    && useradd --uid $USER_UID --gid $USER_GID -m $USER \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USER ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USER \
    && chmod 0440 /etc/sudoers.d/$USER

USER ${USER}
RUN python3 -m pip install --user poetry

## Install oh my zsh
# Uses "Spaceship" theme with some customization. Uses some bundled plugins and installs some more from github
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)" -- \
    -t https://github.com/denysdovhan/spaceship-prompt \
    -a 'SPACESHIP_PROMPT_ADD_NEWLINE="false"' \
    -a 'SPACESHIP_PROMPT_SEPARATE_LINE="false"' \
    -p git \
    -p ssh-agent \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-completions
